version: '3.3'

services:
    db:
        image: mysql:5.6
        restart: always
        ports:
          - 13306:3306
        volumes:
          - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: 1

    wordpress:
        image: wordpress
        restart: always
        depends_on:
          - db
        ports:
          - 8888:80
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: 1
            WORDPRESS_TABLE_PREFIX: wp_

volumes:
    db_data: {}



